### ISSUE TITLE
Not possible to specify multiple examples in responses

### ISSUE THREAD

**Issue by james-siteclick** [asteasolutions/zod-to-openapi#100]
Hi, thanks for the great library!

Open API supports multiple examples in the responses, e.g. see: https://swagger.io/docs/specification/adding-examples/

It seems even if you put them in manually like this:

```
registry.registerPath({
  ...
  responses: {
    404: {
      description: "Testing...",
      content: {
        "application/json": {
          schema: z.object({
            message: z.string()
          }),
          examples: {
            example0: {
              value: {
                message: "Oh no"
              }
            },
            example1: {
              value: {
                message: "Totally gone wrong"
              }
            }
          }
        }
      }
}
```

Then they are stripped in the resulting swagger file.

**Comment by samchungy** [comment]
Ah looks like an easy fix. Just gotta spread the context through here:

https://github.com/asteasolutions/zod-to-openapi/blob/b78918a5c212279174385700dde906f97770f370/src/openapi-generator.ts#L554

**Comment by AGalabov** [comment]
Opened a [PR](https://github.com/asteasolutions/zod-to-openapi/pull/102) for it. cc: @samchungy
