### ISSUE TITLE
Indication of error location

### ISSUE THREAD

**Issue by Aeolun** [asteasolutions/zod-to-openapi#113]
Right now I'm generating an openAPI schema, and only once I run `generateDocument` does the input get validated. There is a field in my schema somewhere that doesn't have the proper types, and `generateDocument` fails with:

```
Missing parameter data, please specify `name` and other OpenAPI parameter props using the `param` field of `ZodSchema.openapi`
```

Unfortunately, this is doesn't really help me address the problem, since I have no idea which field is missing the `name` and other OpenAPI parameter props. Is there a way this error can include where the issue comes from?

**Comment by AGalabov** [comment]
@Aeolun I get your struggles. We've tried adding additional information where we can. I guess the problem here is that you registered a schema without a name at all => the schema would just be something from `zod` and there won't be much we can use to precisely showcase which schema was the problem.

Based on my experience and the error message I would imagine that you did something like:
```ts
headers: [z.string()];

// Or:
headers: [z.string().openapi({ param: { in: 'header' } })];
```

Basically using a headers array (and not an object, since we would've used the keys as name) and not specifying a name from `.openapi`.

**Comment by Aeolun** [comment]
@AGalabov Actually I was using `query: z.unknown(), params: z.unknown()`, because these were old endpoint where I'm not aware of the types.

That wasn't actually the problem though (or at least, it was a problem, but I can sort of see how it's hard to do anything sensible with it). I was going to make a different bug report for that, `zod-to-openapi` seems to try and make the 'z.unknown()' into a list of parameters where the first one is unknown.

My problem was that I have 200 endpoints in my service, and when I run `generateDocument` after adding all 200, the only error that is thrown in the one above. It leads me to know that one of those 200 endpoints probably had a query/params definition that is missing a name, but not which one of the 200 endpoints it is.

It would be helpful if in addition to the information above, it said something like: `Missing parameter data in /api/v1/endpoint POST method: please specify... `.

**Comment by AGalabov** [comment]
@Aeolun actually the `object or undefined` is what we've intended with `AnyZodObject`. However I now see that this might be incorrect. I'll try and see why.

And as for your suggestion I can agree that route information could be used when it comes to a route throwing the error and not a plain parameter (one from the registry definitions).

**Comment by AGalabov** [comment]
@Aeolun 
![image](https://user-images.githubusercontent.com/44395908/229095597-11009878-648c-45e4-afda-91cc87fc13cf.png)

I just added what you've mentioned and TS throws an error that `z.unknown` and `z.string` (and other in general) are not assignable to `z.ZodObject`. How did you manage to pass `z.unknown`?

**Comment by Aeolun** [comment]
That's a good question. Let me recheck my code. Maybe TS lost it's types somewhere.

**Comment by AGalabov** [comment]
@Aeolun did you get to the issue? Meanwhile I've release a new version with parts of your suggestions for including route data into the error. I did not put them in the message but in data. You can try and use the latest [v4.5.3](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v4.5.3) release and check if it helps in your use case.

**Comment by Aeolun** [comment]
@AGalabov Yes, it was indeed in my own code. I'd allowed it to accept unknown as the schema in my own code, and somewhere between there and where it went into openapi the type got lost, so it didn't generate an error at that point.

Apologies for the confusion 🙁
