### ISSUE TITLE
ZodObjects not accepted in some places

### ISSUE THREAD

**Issue by guillempado** [asteasolutions/zod-to-openapi#116]
Hey, congrats for the library. We use it in a formative open source project, but there is not a lot of documentation and we can't find how to achieve some things.

In particular, we would expect to be able to pass ZodObjects to header schemas and to the 'oneOf' key in responses to specify more than one response per code, but they both won't accept them and we don't know what else to try. 

[This is the file](https://github.com/IT-Academy-BCN/ita-wiki/blob/8fdfa9c9688d2783e387415d30bd68458dad5826/back/src/openapi/routes/authRouter.ts) that we are working on with the issues commented out, any help would be appreciated.

**Comment by AGalabov** [comment]
Hello @guillempado, thank you for reaching out.

For this first part ... it seems that we've sadly missed this part and we've not added response headers support. It should be straight forward to add the same interface as the one for request headers. Feel free to open up a PR. If not, I'll try and work on it in the near future.

And for the second one, I'd suggest just using a zod union: 
```ts
400: {
      description: 'Invalid input',
      content: {
        'application/json': {
          schema: z.union([DniErrorResponse, z.string()]), // replace z.string() with whatever you intended to use.
        },
      },
    },
``` 

This would produce the following schema:

```json
"400": {
    "description": "Invalid input",
    "content": {
        "application/json": {
            "schema": {
                "anyOf": [
                    {
                        "$ref": "#/components/schemas/DniErrorResponse"
                    },
                    {
                        "type": "string"
                    }
                ]
            }
        }
    }
}

```

Overall the idea was that you can provide a schema at "root" level. If you opt for `oneOf` you are going into a sort of manual mode. Please let me know if that suits your use case.

**Comment by AGalabov** [comment]
And something more about the headers. Can you verify if the "example" in this test case would work for you - https://github.com/asteasolutions/zod-to-openapi/blob/master/spec/custom-components.spec.ts#L69. I still think that passing zod schemas there might be useful. But if using this approach would suffice for you, I'll defer the work a little bit to target the other issues.

**Comment by guillempado** [comment]
Thanks, the solution with `anyOf` worked nicely. The response header example also worked, but I had to add everything inside a schema property (as seen in [this article](https://swagger.io/docs/specification/authentication/cookie-authentication/) + openapi validation plugins also found it missing):

<img width="791" alt="image" src="https://user-images.githubusercontent.com/28660385/232329943-8f79590b-3a38-4251-a022-906810d31521.png">

<img width="675" alt="image" src="https://user-images.githubusercontent.com/28660385/232328756-f41089c2-5ae6-48ed-9315-4d52952e4aac.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/28660385/232330207-20fc6d51-0ab3-4c0d-86b5-ab85e9556be1.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/28660385/232328888-35ce3808-1e4c-4804-9000-f649fece6290.png">

I also tried to modify the interface to pass Zod objects (in the installed npm package, v4.5.2):
<img width="837" alt="image" src="https://user-images.githubusercontent.com/28660385/232332001-1d5696c0-4757-444c-9858-7c5f6c9fd721.png">

<img width="733" alt="image" src="https://user-images.githubusercontent.com/28660385/232332329-8d81f177-00b3-43cd-a046-634f120d1de8.png">
Either / or:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/28660385/232332249-8c04e07b-4bc0-4cc1-89d0-44071c54b2c1.png">

But the Yaml parser breaks:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/28660385/232332295-ace790b2-5d4d-41fe-9627-db9d1b139450.png">

**Comment by MattIPv4** [comment]
👋 Would just like to +1 zodobjects being supported for header schemas (both in parameters and responses)

**Comment by AGalabov** [comment]
@guillempado @MattIPv4 - I've opened a [PR](https://github.com/asteasolutions/zod-to-openapi/pull/128) for this. Please feel free to check the test case - it should provide you with enough information on how it would be used. Please pay attention to the usage of `param` in `.openapi` and where do the properties end up in the resulting schema. Let me know if that does not meet your expectations.

And aslo @MattIPv4 I do believe that request headers should already support `ZodObject` - see [this test case](https://github.com/asteasolutions/zod-to-openapi/blob/master/spec/routes/parameters.spec.ts#L61)
