### ISSUE TITLE
UnknownZodTypeError  with object with default value

### ISSUE THREAD

**Issue by blade2005** [asteasolutions/zod-to-openapi#12]
When using a default value I'm getting the below error.
```
UnknownZodTypeError {
  message: 'Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.',
  data: {
    currentSchema: {
      innerType: [ZodString],
      defaultValue: [Function (anonymous)],
      typeName: 'ZodDefault',
      openapi: [Object]
    },
    schemaName: 'Object'
  }
}
```

Problem code
```
registry.register("Object", z.string().openapi({ description: "object" }).default(""));

```

**Comment by AGalabov** [comment]
Hello @blade2005,

Thank you for using `asteasolutions/zod-to-openapi` and reporting your problem. Yes, `default` values are not currently handled. It would be a straight forward feature to implement. I'll add it to a new release tomorrow morning.

In the meantime you can provide a type by using  `.openapi({ type: 'string' })` to avoid the overall error.

**Comment by AGalabov** [comment]
Added in the `v1.2.0` release.
