### ISSUE TITLE
Support for z.refine

### ISSUE THREAD

**Issue by blade2005** [asteasolutions/zod-to-openapi#13]
Seeing the following error. I don't think `z.refine()` is supported
```
UnknownZodTypeError {
  message: 'Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.',
  data: {
    currentSchema: {
      schema: [ZodObject],
      typeName: 'ZodEffects',
      effect: [Object],
      openapi: [Object]
    },
    schemaName: 'Object'
  }
}```

**Comment by AGalabov** [comment]
Hello @blade2005,

Thank you for using `asteasolutions/zod-to-openapi` and reporting your problem. Yes, `refine` options are not currently handled. It would be a straight forward feature to implement. I'll add it to a new release tomorrow morning.

In the meantime you can provide a type by using  `.openapi({ type: 'object' })` to avoid the overall error.

**Comment by AGalabov** [comment]
Added in the `v1.2.0` release.

**Comment by elmeister** [comment]
Can we also add support for  `ZodEffects` to `RouteConfig.request` options please? 
Would be nice to be able to use `.transform()` for `request.body` for example - directly, and not add it only after passing schema to `.registerPath()`

**Comment by AGalabov** [comment]
@elmeister there are a couple of things that I get from your request:

1. Support for ZodEffects in `request.body`. I believe this one is already present.
2. Support for `.transform` - this request we've labeled impossible (also mentioned in the `README.md`
3. Overall it wouldn't be correct to support transform for your body. Let's say you have an API that has the following body schema:
```ts
const schema = z.object({ id: z.string().transform(val => Number(val)) })
```
in that case the actual API accepts a `string` and this is what the documentation should be as well, isn't it?

And finally - if you feel like there is still something that we can improve on based on my comments - please feel free to open up an issue.
