### ISSUE TITLE
Unable to pass string as argument to `z.openapi`

### ISSUE THREAD

**Issue by Siegrift** [asteasolutions/zod-to-openapi#130]
Hi, thanks for this amazing library. I found one issues which is currently a blocker for me.

See: 

<img width="234" alt="image" src="https://user-images.githubusercontent.com/22679154/236384506-345d25d0-9b4b-47fe-a758-8e3d6a9c118a.png">

I am trying to generate a swagger from my schema and want to reference the my error schema for multiple open API components. I didn't come up with a way how to do this.

**Comment by AGalabov** [comment]
Hey @Siegrift what you are trying to do is not yet released. It would be as a new major release (v5.0.0). However we want to make a few other improvements before releasing it. I imagine you saw that from the README in github which references `master`.  You can follow the [latest released README instead](https://github.com/asteasolutions/zod-to-openapi/tree/release/v4.6.1) for the time being.

**Comment by Siegrift** [comment]
Oh, I see. Thanks. 

Maybe it would make sense to have a small notice at the beginning of the README that the master contains the unreleased docs version. But feel free to close this issue.
