### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'Partial<ZodOpenAPIMetadata<{ name: string; id: string; age: number; }, { name: string; id: string; age: number; }>>'

### ISSUE THREAD

**Issue by elbassel** [asteasolutions/zod-to-openapi#135]
When I tried the basic example here, it gives:
 TS2345: Argument of type 'string' is not assignable to parameter of type 'Partial<ZodOpenAPIMetadata<{ name: string; id: string; age: number; }, { name: string; id: string; age: number; }>>'.

```
import {
	OpenAPIGenerator,
	OpenAPIRegistry,
	extendZodWithOpenApi,
} from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';

const UserSchema = z
	.object({
		id: z.string().openapi({ example: '1212121' }),
		name: z.string().openapi({ example: 'John Doe' }),
		age: z.number().openapi({ example: 42 }),
	})
	.openapi('User');
```

package.json:
```
{
  "name": "test-zod-api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@asteasolutions/zod-to-openapi": "^4.6.2",
    "@types/node": "^20.1.2",
    "ts-node": "^10.9.1",
    "zod": "^3.21.4"
  }
}

```

**Comment by AGalabov** [comment]
Hello @elbassel I am glad you are using this library. What you are trying to do is not yet released. It would be as a new major release (v5.0.0). However we want to make a few other improvements before releasing it. I imagine you saw that from the README in github which references master. You can follow the [latest released README instead](https://github.com/asteasolutions/zod-to-openapi/tree/release/v4.6.1) for the time being.

See the same being reported [here](https://github.com/asteasolutions/zod-to-openapi/issues/130)
