### ISSUE TITLE
Description Not Being Set on Params Object in registerPath() method

### ISSUE THREAD

**Issue by tmcallister92** [asteasolutions/zod-to-openapi#137]
Hey all, 

Thanks for the awesome library, we have loved playing around with it and plan on using it on some upcoming API work. 

We are seeing some unexpected behavior attempting to append metadata to the `params` object, typically the metadata is on the `params` itself, not on the `schema` for the params (where it is currently being rendered).

We are expecting this configuration:

![repro1](https://github.com/asteasolutions/zod-to-openapi/assets/23154605/708f2683-7bb4-4fa4-bebf-36d5b7d96723)

To generate this result

![repo2](https://github.com/asteasolutions/zod-to-openapi/assets/23154605/d123a442-799b-4347-82a4-d146f3e6af9d)

We have also tried with this configuration (which yields no result in rendered yaml):

![image](https://github.com/asteasolutions/zod-to-openapi/assets/23154605/0498647e-93d7-44b6-ac86-03fb0d1bb4aa)

Minimum Repo 

```
import {
  OpenAPIGenerator,
  OpenAPIRegistry,
  extendZodWithOpenApi,
} from '@asteasolutions/zod-to-openapi';
import writeYamlFile from 'write-yaml-file';
import { z } from 'zod';

extendZodWithOpenApi(z);

async function main() {
  const registry = new OpenAPIRegistry();

  const tags = [
    {
      name: 'Shop',
      description: 'Data and operations related to shop',
    },
  ];

  const shopComponent = 'Shop';
  registry.register(shopComponent, z.object({ name: z.string() }));

  // paths ************************************************************

  // get a shop
  registry.registerPath({
    method: 'get',
    path: '/shop/{shopId}',
    tags: ['Shop'],
    description:
      'Retrieve shop data needed to render a widget and request protection quotes',
    summary: 'Get a shop',
    request: {
      params: z.object({
        shopId: z
          .string()
          .openapi({ description: 'A UUID belonging to the store' }),
      }),
    },
    responses: {
      200: {
        description: 'OK',
      },
    },
  });

  const generator = new OpenAPIGenerator(registry.definitions, '3.0.0');

  const generateDocument = generator.generateDocument({
    info: {
      version: '0.0.1',
      title: 'Shop Demo API',
      description:
        'This is the Shop API.',
      contact: { email: 'support@corso.com' },
    },
    servers: [
      { url: 'https://demo.api.corso.com' },
    ],
    tags,
  });

  // write the yaml representation
  await writeYamlFile(`./demo-oas.yaml`, generateDocument);
}

main().catch((err) => console.error(err));
```

```
Dependencies 
   asteasolutions/zod-to-openapi:  ^4.6.2,
   zod: ^3.5.1,
   nodejs 18.11.0
```
Attempted fixes: 

Updating to latest Zod and zod-to-openapi versions

**Comment by AGalabov** [comment]
@tmcallister92 thank you for the elaborate description.

I'll try and answer step by step:
1. The root level description is for the path/route/endpoint itself so it shouldn't propagate down to the particular parameter
2. Adding a description to the whole parameters is also incorrect - the description is not on the entire set of parameters but rather on the exact one `shopId` (the string)
3. The minimal repo is actually quite close - but in this case you are specifying the description on the "schema" level and not on the param level.

What you want to do can be achieved with the usage of `.openapi({ param: { description: 'A UUID belonging to the store' })` as partially mentioned [here](https://github.com/asteasolutions/zod-to-openapi/issues/137).


So bascially you'd have this:
```ts
request: {
    params: z.object({
      shopId: z
        .string()
        .openapi({ param: { description: 'A UUID belonging to the store' } }),
    }),
},
```

and the result should be this (in JSON):
```json
"parameters": [
    {
        "schema": {
            "type": "string"
        },
        "required": true,
        "description": "A UUID belonging to the store",
        "name": "shopId",
        "in": "path"
    }
],
```

**Comment by tmcallister92** [comment]
@AGalabov Thanks for the prompt response, that worked as I assumed it would. Great package 👍

**Comment by talyh** [comment]
I just landed here after struggling with the same issue
Maybe it's already in the docs and I missed it, but I couldn't see anything there about ` .openapi({ param: { description: 'A UUID belonging to the store' } })`

May be worth making it more evident/explicit
