### ISSUE TITLE
Support for oneOf and anyOf for alternate schemas for the response body

### ISSUE THREAD

**Issue by codeinabox** [asteasolutions/zod-to-openapi#138]
Great library, thank you for creating it! I have a question, does it support [oneOf and anyOf for alternate schemas for the response body](https://swagger.io/docs/specification/describing-responses/)?

**Comment by codeinabox** [comment]
I found the answer in https://github.com/asteasolutions/zod-to-openapi/issues/76

**Comment by AGalabov** [comment]
Thank you for the kind wors @codeinabox. And yes that was the answer.
