### ISSUE TITLE
`z.nullable` does not use schema references

### ISSUE THREAD

**Issue by FelixZY** [asteasolutions/zod-to-openapi#141]
I have a schema like this:

```typescript
  parentVenue: z.nullable(ProfileReferenceDTOSchema).openapi({
    description:
      'A venue to which this venue belongs.\n\nFor example, the theoretical venue "Dance Palace" may be the parent venue of the venues "Indoors" and "Outdoors"',
  }),
  childVenues: z.array(ProfileReferenceDTOSchema).openapi({
    description:
      'The venues that belong to this venue.\n\nFor example, the theoretical venues "Indoors" and "Outdoors" may be child venues of the venue "Dance Palace"',
  }),
```

Which causes an annoying difference when rendered:
![Screenshot from 2023-05-18 21-37-27](https://github.com/asteasolutions/zod-to-openapi/assets/2656517/61067829-34b8-49bf-9dd5-c992eed77cc0)

It seems the reason for this is that the openapi spec generated for `z.array` uses
```json
"type": "array",
"items": {
  "$ref": "#/components/schemas/profiles.ProfileReferenceDTO"
},
```

whereas the openapi spec generated for `z.nullable` does not use `$ref` (tested for openapi `3.0.3` and `3.1.0`):
```json
"type": "object",
"nullable": true,
"properties": {
  "id": { "type": "string", "format": "uuid" },
  "name": { "type": "string" },
  "type": {
    "type": "string",
    "enum": ["organization", "individual", "venue"]
  },
  "images": {
    "$ref": "#/components/schemas/storage.ImageDTO"
  }
}
```

Would it be possible to get `z.nullable` to generate a `$ref` as well? Perhaps using `oneOf`?

**Comment by AGalabov** [comment]
@FelixZY thanks for bringing this up. `nullable`s are tricky since they behave differently based on the chosen OpenApi version (3.0 or 3.1). I'll try and take a look asap, but right now we are hoping to release a new major version and I'll probably have to prioritize the feature requests of the other open issues slightly higher. Sorry for that, and I'll come back to you as soon as I can. In the mean time feel free to give it a go and open a PR yourself.

**Comment by AGalabov** [comment]
@FelixZY I took a look at your example. And actually we already support that. The result has `allOf`. However we've only currently done the required support on `schema.nullable()` and not on `z.nullable(schema)`. I'll open a PR soon but you can also fix this on your end (functionally there shouldn't be any difference for you).

**Comment by AGalabov** [comment]
This turned out to be impossible with the current way of implementing such methods. Because of that I've just updated the README.md file with a note for it (that `schema.nullable()` should be used instead)
