### ISSUE TITLE
Is it possible to have multiple request schemas?

### ISSUE THREAD

**Issue by jmdrawneek** [asteasolutions/zod-to-openapi#151]
How would I go about implementing this?
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof

It looks like the schemas seem to overwrite each other at the moment.

I'm currently using version 4.3.

**Comment by jmdrawneek** [comment]
I've managed to generate working json (checked via https://editor.swagger.io/).

But the page generates with both the request body and response as undefined.

**Comment by AGalabov** [comment]
Hey @jmdrawneek  the way you can achieve this is by using `z.union`. For example: 

```ts
const petSchema = registry.register('Pet', z.object({ type: z.string() }));
const personSchema = registry.register('Person', z.object({ age: z.number() }));

const path = registry.registerPath({
  // other props here
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.union([petSchema, personSchema]),
        },
      },
    },
  },
});
```

which generates

```json
"requestBody": {
    "content": {
        "application/json": {
            "schema": {
                "anyOf": [
                    {  "$ref": "#/components/schemas/Pet" },
                    { "$ref": "#/components/schemas/Person" }
                ]
            }
        }
    }
```

Hope that helps. I'll close the isue. However, if you have further questions please reopen the issue and share an example of the zod schemas that you are trying to use.
