### ISSUE TITLE
The requested module 'npm:@asteasolutions/zod-to-openapi' does not provide an export named 'OpenAPIGeneratorV3'

### ISSUE THREAD

**Issue by ryoppippi** [asteasolutions/zod-to-openapi#153]
I thins `OpenAPIGeneratorV3` in README is not correct.
Maybe `OpenApiGeneratorV3`?

**Comment by AGalabov** [comment]
Yes thank you. This has also been mentioned in #148. Fixed it for [v5.2.0](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v5.2.0)
