### ISSUE TITLE
Combine config.parameters with ones generated from config.request

### ISSUE THREAD

**Issue by vosmol** [asteasolutions/zod-to-openapi#164]
Hey 👋🏻. Currently when using `registerPath` method if both fields `RouteConfig.parameters` and `RouteConfig.request` are defined, `parameters` field is overwritten by the `request` field. 

Would it be possible to combine these two fields? 

I encountered this when i tried to do this 👇🏻 as cookies field is not currently present in the request object:

```
registry.registerPath({
      ...
      parameters: [
        {
          in: 'cookie',
          name: 'sessionCookie',
        },
      ],
      request: {
        query: z.object({
          id: z.string(),
        }),
      },
    });
```

which results in:
```
parameters: [
      {
        schema: { type: 'string' },
        required: true,
        name: 'id',
        in: 'query'
      }
]
```

instead of:

```
parameters: [
      { in: 'cookie', name: 'sessionCookie' },
      {
        schema: { type: 'string' },
        required: true,
        name: 'id',
        in: 'query'
      }
]
```

**Comment by AGalabov** [comment]
@vosmol thank you for your contribution. I've released [v5.5.0](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v5.5.0) that supports this as well (even with the added support for cookies, it makes sense to have it as a manual approach if someone needs it)
