### ISSUE TITLE
Handling of multiple chained `regex` calls

### ISSUE THREAD

**Issue by samkio** [asteasolutions/zod-to-openapi#169]
I'm not sure if this is possible but I would like clarity on how this works or how it should work.

If we imagine a schema such as:
```typescript
z.string()
      .regex(pattern1, "Must match this regex")
      .regex(pattern2, "And this regex too")
```

Then after transforming we get a pattern of `pattern1` in the OpenAPI spec. i.e. `pattern2` is lost here.
The issue being that whilst zod supports multiple regex checks, OpenAPI spec only allows for one.
Other zod to openapi libraries either have this semantic or try to combine the two patterns.

What should the semantic be here? Was it intentional that the first pattern is picked? Or should it attempt to combine the regex patterns? Something like `(?=match this expression)(?=match this too)` could be clear in terms of documentation?

I raise this as we have scenarios where we have multiple regex checks and the generated docs could be misleading.

**Comment by samkio** [comment]
Hey @AGalabov ,

Thanks for taking a look. My understanding is that it is an "and", but I suppose someone could create more complex schemas with `.and` and `.or` in zod.

Potentially this would be difficult to automate and manually fixing, as you've suggested, may be the best option in these scenarios.

**Comment by AGalabov** [comment]
@samkio  as you mentioned I think it would be much cleaner for us to leave such a special case to the "user" instead of guessing and making a best effort of "matching it" and potentionally generating something wrong.

I'll be closing the issue. And still thank you for bringing it up and using our library
