### ISSUE TITLE
Add support for `z.bigint()`

### ISSUE THREAD

**Issue by redfoxlee** [asteasolutions/zod-to-openapi#176]
Currently this code

```typescript
const registry = new OpenAPIRegistry();
registry.register("BigintSchema", z.bigint());

const generator = new OpenAPIGenerator(registry.definitions, "3.0.0");

try {
  const document = generator.generateDocument({
    info: {
      version: "1.0.0",
      title: "My API",
    },
    servers: [{ url: "v1" }],
  });
  console.log(document);
} catch (err) {
  console.error(err);
}
```
Throws this error
```sh
UnknownZodTypeError {
  message: 'Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.',
  data: {
    currentSchema: {
      checks: [],
      typeName: 'ZodBigInt',
      coerce: false,
      openapi: [Object]
    },
    schemaName: 'BigintSchema'
  }
}
```
Ideally, it would generate an OpenAPI spec like other supported data types.

**Comment by redfoxlee** [comment]
I just realized that below can be used as an alternative for an _ID_ field (not what i expected but i can live with that).
```typescript
z.bigint().optional().openapi('refname', {
    format: 'int64',
    type: 'integer',
})
```
However, `minimum` and `maximum` (and more) are not work since they were originally defined as `number` in the _SchemaObject_ :-(

**Comment by AGalabov** [comment]
@redfoxlee thank you for that. Yes `bigint` should be supported on our side - it was reltively newly introduced to `zod`. I'll definitely add the expected support whenver I can. But yes in the mean time you've correctly identified a way to handle it.

And as for `minimum` and `maximum` I did not quite get what doesn't work?
Did you mean that:
```ts
z.bigint().min(3).max(5)
``` 
or
```ts
z.bigint().openapi('refname', {
  format: 'int64',
  type: 'integer',
  minimum: 3,
  maximum: 5
})
```
doesn't work? I believe the second one should still be valid. And if is the first one - yes that should be supported as well. Please let me know

**Comment by redfoxlee** [comment]
Hi, @AGalabov Thank you so much! And Sorry for the late response.

I'll try this once i commit this comment!

> And as for minimum and maximum I did not quite get what doesn't work?

Oh...I tried to implement this once, but failed to define `minimum` and `maximum` in the test code like this:

```typescript
z.bigint().openapi('refname', {
  format: 'int64',
  type: 'integer',
  minimum: 3n,
  maximum: 5n
})
```

i know it's stupid...
