### ISSUE TITLE
support z.intersection for query parameter

### ISSUE THREAD

**Issue by Pyrolistical** [asteasolutions/zod-to-openapi#181]
Env
```
$ node -v
v20.8.0
$ ack zod package.json  
    "@asteasolutions/zod-to-openapi": "6.2.0",
    "zod": "3.22.4"
```

Given `repo.js`
```js
import { z } from "zod";
import {
  OpenAPIRegistry,
  OpenApiGeneratorV31,
  extendZodWithOpenApi,
} from "@asteasolutions/zod-to-openapi";
extendZodWithOpenApi(z);

const registry = new OpenAPIRegistry();

registry.registerPath({
  method: "get",
  path: "/z.object-works",
  request: {
    query: z.object({
      a: z.string(),
      b: z.number(),
    }),
  },
  responses: {
    200: {
      content: {
        "application/json": {
          schema: z.object({}),
        },
      },
    },
  },
});

registry.registerPath({
  method: "get",
  path: "/z.intersection-fails",
  request: {
    query: z.intersection(
      z.object({
        a: z.string(),
      }),
      z.object({ b: z.number() })
    ),
  },
  responses: {
    200: {
      content: {
        "application/json": {
          schema: z.object({}),
        },
      },
    },
  },
});

const generator = new OpenApiGeneratorV31(registry.definitions);

generator.generateDocument({
  openapi: "3.1.0",
});
```

Run `node repo.js`

## Expected
No error

## Actual
```
$ node repo.js

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
MissingParameterDataError {
  message: 'Missing parameter data, please specify `name` and other OpenAPI parameter props using the `param` field of `ZodSchema.openapi`',
  data: {
    missingField: 'name',
    location: 'query',
    route: 'get /z.intersection-fails'
  }
}

Node.js v20.8.0
```

I think the issue is here: https://github.com/asteasolutions/zod-to-openapi/blob/81d16d59412e25533dc23dae1aad8210fcbd0605/src/openapi-generator.ts#L1191

**Comment by AGalabov** [comment]
@Pyrolistical  thank you for bringing this up. I'll try a take a look at it soon.

**Comment by AGalabov** [comment]
@Pyrolistical a couple of things.

1. I only just noticed that you are using a plain JS file. If you had TS definitions you'd see that we do not support a `ZodIntersection` for query parameters
2. And I don't think we should. In general a `z.intersection ` can be used with any types => `z.intersection(z.string(), z.number());` - not sure how we are supposed to produce a documentation from this.

We could theoretically try and enforce **only** intersections of two zod objects - but even then we would need to "compute" what the outcome of it and somehow construct it as if it is an object. Not sure we want to do that.

In general `ZodIntersection` is supported as a schema and it produces an `anyOf` documentation, however that is not a valid format for parameters.

I'd personally close this as "Won't Do" and suggest you simply provide an alternate schema or use the `.openapi` method to provide documentation manually. cc: @georgyangelov for a second opinion

**Comment by Pyrolistical** [comment]
But my repo case is intersection of two objects which does make sense as a parameter

**Comment by georgyangelov** [comment]
@Pyrolistical can you provide a more real-world example? Also in your case is it possible to use `Schema.merge` instead? As that only works with objects and that's what we want - only objects make sense for parameters.

**Comment by Pyrolistical** [comment]
@georgyangelov ah, yes. `z.merge` will work for me
