### ISSUE TITLE
context is lost when using transform

### ISSUE THREAD

**Issue by treboryx** [asteasolutions/zod-to-openapi#184]
The following code:

```ts
import { OpenAPIRegistry, OpenApiGeneratorV3, extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi'
import { AnyZodObject, z } from 'zod'
import { mapKeys, camel } from 'radash'

extendZodWithOpenApi(z)

const registry = new OpenAPIRegistry()

const bodySchema = z
  .record(z.string())
  .transform((x) => mapKeys(x, camel))
  .pipe(
    z.strictObject({
      fieldId: z.string().nullish().openapi({
        description: 'Test Field ID'
      }),
      errorType: z.string().openapi({
        description: 'Error Type'
      })
    })
  ) as unknown as AnyZodObject

registry.register('body', bodySchema)
const generator = new OpenApiGeneratorV3(registry.definitions)
const component = generator.generateComponents()

console.log(JSON.stringify(component, null, 2))
```

will produce the following schema in the spec:
```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

So the context & actual schema is lost, which is incorrect.

If `record`, `transform` and `pipe` are not used and instead just the `strictObject` it'll produce the correct schema in the spec:

```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "properties": {
            "fieldId": {
              "type": "string",
              "nullable": true,
              "description": "Test Field ID"
            },
            "errorType": {
              "type": "string",
              "description": "Error Type"
            }
          },
          "required": ["errorType"],
          "additionalProperties": false
        }
      }
    }
  }
}
```

**Comment by AGalabov** [comment]
@treboryx the "problem" here is the `pipe` operator and your expectation towards it. We implemented the support for it in this PR with this comment: https://github.com/asteasolutions/zod-to-openapi/pull/118#issue-1669555907 

We've taken the decision that the "in" part of a pipe is what should be used as the source for documentation.

The main argument behind it is that people use zod for validation and that is what their documentation should represent. In your case the input form of your API is a record of strings. What you do in the transform and later on in the pipe becomes "application logic" and not "incoming request logic".

So I would say that this works "as expected". However I can try and give you some pointers:
1. You can always use `.openapi` to override anything - you can simply pass in a manually written documentation. That is obviously not ideal but I imagine this is a singular instance for you
2. You could restructure your validation to:

```ts
const bodySchema = z.preprocess(
  x => mapKeys(x, camel),
  z.strictObject({
    fieldId: z.string().nullish().openapi({
      description: 'Test Field ID',
    }),
    errorType: z.string().openapi({
      description: 'Error Type',
    }),
  })
);,
```
And I am not saying this just as a mean to "make it work with our library" but rather as an attempt to streamline your code. I.e from what I understand you don't intend to receive a record - that's just a "boilerplate" root schema (it could've been z.any() for that matter). And by using an actual schema AND a `preprocess` you showcase this in a slighly more obvious way. 
P.S.I might be wrong here.

Please let me know if those make sense and work for you.

**Comment by ThatKawaiiSam** [comment]
> @treboryx the "problem" here is the `pipe` operator and your expectation towards it. We implemented the support for it in this PR with this comment: [#118 (comment)](https://github.com/asteasolutions/zod-to-openapi/pull/118#issue-1669555907)
> 
> We've taken the decision that the "in" part of a pipe is what should be used as the source for documentation.
> 
> The main argument behind it is that people use zod for validation and that is what their documentation should represent. In your case the input form of your API is a record of strings. What you do in the transform and later on in the pipe becomes "application logic" and not "incoming request logic".
> 
> So I would say that this works "as expected". However I can try and give you some pointers:
> 
> 1. You can always use `.openapi` to override anything - you can simply pass in a manually written documentation. That is obviously not ideal but I imagine this is a singular instance for you
> 2. You could restructure your validation to:
> 
> ```ts
> const bodySchema = z.preprocess(
>   x => mapKeys(x, camel),
>   z.strictObject({
>     fieldId: z.string().nullish().openapi({
>       description: 'Test Field ID',
>     }),
>     errorType: z.string().openapi({
>       description: 'Error Type',
>     }),
>   })
> );,
> ```
> 
> And I am not saying this just as a mean to "make it work with our library" but rather as an attempt to streamline your code. I.e from what I understand you don't intend to receive a record - that's just a "boilerplate" root schema (it could've been z.any() for that matter). And by using an actual schema AND a `preprocess` you showcase this in a slighly more obvious way. P.S.I might be wrong here.
> 
> Please let me know if those make sense and work for you.

Hey @AGalabov, that seems to work perfectly for body schema!

We do however get the following error typing to apply that `preprocess` method to the query parameters.

```
Missing parameter data, please specify `name` and other OpenAPI parameter props using the `param` field of `ZodSchema.openapi`
```

The transform does apply but generating the OpenAPI document does generate that error.

**Comment by AGalabov** [comment]
@ThatKawaiiSam thank you for confirming. This sounds like an issue no our side. I'll try and reproduce it and fix it.

**Comment by AGalabov** [comment]
@ThatKawaiiSam I tried this locally and I think I know what happened:

Let's say this is the bodySchema:
```ts
const bodySchema = z.preprocess(
  x => x,
  z.strictObject({
    fieldId: z.string().nullish().openapi({
      description: 'Test Field ID',
    }),
    errorType: z.string().openapi({
      description: 'Error Type',
    }),
  })
);
```

### This works
```ts
registry.registerPath({
  request: {
    params: z.object({ test: bodySchema }),
  },
  // Rest
});
```

### This does not work
```ts
registry.registerPath({
  request: {
    params: bodySchema as any, // notice how in Typescript I had to cast this
  },
  // Rest
});
```

The problem here is that with request params/query/headers we've used `ZodObject` as a format defined. We depend on the fact that this is the representation of such parameters over the network. So we kind of enforce a `ZodObject` instance to be passed here. And in your case you are passing a "preprocessed object". I don't think I want to add support for that.

What I can suggest is to rather `preprocess` each parameter "manually" in such a case. Looking at your code I imagine it translates to the following (looking at mapKeys)

```ts
const parameterSchema = z.strictObject({
  fieldId: z.preprocess(camel, z.string().nullish()).openapi({
    description: 'Test Field ID',
  }),
  errorType: z.preprocess(camel, z.string()).openapi({
    description: 'Error Type',
  }),
});

```

I know that's not ideal, but again - I do not think we want to allow preprocessed objects as root level parameter. I hope you understand.
