### ISSUE TITLE
Coerce drops required option on output

### ISSUE THREAD

**Issue by Bram-dc** [asteasolutions/zod-to-openapi#185]
When using coerce the required option is no longer there when outputting openapi.json

Input:
![image](https://github.com/asteasolutions/zod-to-openapi/assets/13683918/0657188b-8bd3-47a0-97da-2d03a0d827ac)

Output:
![image](https://github.com/asteasolutions/zod-to-openapi/assets/13683918/aa7d8cbc-0a18-4536-bcb1-19c71fb872a1)

**Comment by Bram-dc** [comment]
This is probably due to .isNullable() being true on the zod object and is maybe the correct way for this library to also define the required option.

**Comment by AGalabov** [comment]
Yes @Bram-dc you are totally correct - the capabilities of null/undefined is what is causing this change and it is expected

**Comment by Sozialarchiv** [comment]
I have the same issue.
```
const t = z.number({description: 'Database ID', coerce: true})
t.isNullable() // true
t.isOptional() // false
```
Would it be an option to test isOptional in case of request params?

**Comment by tonyd33** [comment]
Bump on this. In the meantime, in case others stumbled upon this and are new to this library and OpenAPI like I am, we can override `required` by setting `param.required` to true in the `.openapi` metadata. Example:
```
const paramsSchema = z.object({
  userId: z.coerce
    .number()
    .openapi({param: { required: true, example: 1, description: 'User id' }});
});
```

**Comment by mbrevda** [comment]
is there a way to override `"nullable": true`, too?
