### ISSUE TITLE
@shaikegross thank you for contributing. While the PR looks perfectly fine, we've intentionally not added this within our code base.

### ISSUE THREAD

**Issue by shaikegross** [asteasolutions/zod-to-openapi#186]
@shaikegross thank you for contributing. While the PR looks perfectly fine, we've intentionally not added this within our code base.

Please see this comment: https://github.com/asteasolutions/zod-to-openapi/pull/51#discussion_r996428248

TLDR: There is a `date-time` format but there is also just `date`. So from a generation standpoint we cannot assume on behalf of the user.

As for:
> The only way to do this without having to hack the generator is to c;hange the openapi schema creatd from ZodDate objects to have a format type
That should not be true - you can use the `.openapi` method to do:

```ts
const schema = z.date().openapi({ format: 'date-time' });
```

Please let me know if that answers your questions and works for you

_Originally posted by @AGalabov in https://github.com/asteasolutions/zod-to-openapi/issues/183#issuecomment-1801803273_

Great! really appreciate the feedback. just one small thing, was there a place in documentation where I could tell that I can use to `format` property on any zod object other than string, cause I only saw it mentioned for `ZodString`

**Comment by AGalabov** [comment]
@shaikegross the idea in the line in the README was more towards (we support automatic `format` from some modifiers of `ZodString`). In general any property you want can be added using the `openapi` method:

> .openapi({ [key]: value }) - this way we can specify any OpenApi fields. For example z.number().openapi({ example: 3 }) would add example: 3 to the generated schema.

Using `.openapi` is kind of our way to give manual control to users to do whatever they like - they are always taken with higher priority => it can be used to override stuff as well.

Still thank you for pointing out that there was something you are missing from the documentation. We do plan to improve upon it soon. I'll close this ticket for now. Let me know if I can help with anything else
