### ISSUE TITLE
using post request

### ISSUE THREAD

**Issue by colindotfun** [asteasolutions/zod-to-openapi#204]
how can i add a schema for the data on an incoming post request?

it doesnt seem to just accept a z.object()

e.g.

```
registry.registerPath({
  method: "post",
  path: "/whatever",
  description: "Do something.",
  requestBody: {
    // what goes here?
  },
  responses: {
    200: {
      description: "Object with user data.",
      content: {
        "application/json": {
          schema: $MySchema,
        },
      },
    },

  },
})
```

**Comment by AGalabov** [comment]
@colinricardo the correct place to use this would be inside the `request.body` property instead. Iti s mentioned in this section https://nextjs.org/docs/app/building-your-application/routing/route-handlers

**Comment by longnt-nami** [comment]
Please reopen this. Ran into this problem lately. How to use registerPath with post request? Got undefined data from body

**Comment by AGalabov** [comment]
Are you using request.body and not the `requestBody` field as suggested above? Can you give an example. Only then can I reopen it
