### ISSUE TITLE
Support ES Modules?

### ISSUE THREAD

**Issue by yusukebe** [asteasolutions/zod-to-openapi#219]
Hi.

First, thank you very much for creating such a great product. We use Zod to OpenAPI in [`@hono/zod-openapi`](https://github.com/honojs/middleware/tree/main/packages/zod-openapi). It can only be archived if Zod to OpenAPI exists.

What I would like to know/suggest is supporting ES Modules. Currently, this only supports Common JS. However, some environments, such as Vitest, use only ES Modules and do not support Common JS. So the following problem occurred:

https://github.com/honojs/middleware/issues/436

Would you happen to have any plans to support ES Modules? If so, it will be a great opportunity to work Zod to OpenAPI in more environments. Thanks!

**Comment by georgyangelov** [comment]
Hi @yusukebe,

We're definitely open to supporting ESM, however time we can put in the project is limited lately so I can't promise anything in terms of time.

Will you be ok to help on this? I believe it should be mostly splitting our tsconfig to tsconfig.cjs.json and tsconfig.esm.json, updating the build scripts and adding to the package.json. Plus some testing of course, and it would help that you have a reproduction case through your library. What do you think?

**Comment by danielkarso-pon** [comment]
I just added a PR for this: https://github.com/asteasolutions/zod-to-openapi/pull/220

I haven't tested it yet however.

**Comment by yusukebe** [comment]
@georgyangelov  Thank you for your response!

@danielkarso-pon So quick handling. Great!

**Comment by ducan-ne** [comment]
I encountered an issue while integrating the new Cloudflare Worker Vitest plugin. After hours of debugging, I noticed that openapi3-ts supports mjs, but @asteasolutions/zod-to-openapi (which import openapi3-ts) does not, makes vitest/cloudflare worker forces to use cjs, causing my test to fail. I hope to see this addressed in the next release.

**Comment by danielkarso-pon** [comment]
Fyi; if you want vitest fixed for now and not wait for the next release you can do this in your 

`package.json`

```
"dependencies": {
    "@cloudflare/itty-router-openapi": "^1.0.14",
    "luxon": "^3.4.4",
    "openmeteo": "^1.1.3",
    "toucan-js": "^3.3.1",
    "zod": "^3.22.4",
    "zod-to-openapi": "github:danielkarso-pon/zod-to-openapi#multi-package"
  },
  "overrides": {
    "@asteasolutions/zod-to-openapi": "$zod-to-openapi"
  }
```

And in your `vitest.config.ts`

```
import { defineWorkersConfig } from '@cloudflare/vitest-pool-workers/config';
import path from 'node:path';

export default defineWorkersConfig({
	test: {
		poolOptions: {
			workers: {
				wrangler: { configPath: './wrangler.toml' },
			},
		},
		server: {
			deps: {
				inline: ['@asteasolutions/zod-to-openapi'],
			}
		},
	},
	resolve: {
		alias: {
			'@/': new URL('./src/', import.meta.url).pathname,
			'@asteasolutions/zod-to-openapi': path.resolve(__dirname, 'node_modules/zod-to-openapi/dist/mjs/index.js'),
			'openapi3-ts/oas30': path.resolve(__dirname, 'node_modules/openapi3-ts/dist/oas30.mjs'),
		},
	}
});

```

**Comment by yusukebe** [comment]
@danielkarso-pon @AGalabov 

I've confirmed it works well! I'll release the new version of `@hono/zod-openapi` that includes the release. Thanks so much!
