### ISSUE TITLE
How to set section names

### ISSUE THREAD

**Issue by perry-mitchell** [asteasolutions/zod-to-openapi#22]
Hi,

When taking the generated output from `generateDocument`, and passing it into a Swagger UI generator, the section title doesn't seem to be customisable (and is just left as "default):

![image](https://user-images.githubusercontent.com/3869469/174953975-802d8178-8548-4f56-95f2-68c3579015c9.png)

Is there some way to customise this that I missed?

**Comment by AGalabov** [comment]
Hello @perry-mitchell,

I believe what you're looking for is passing `tags: ['Some tag'],` where you register the route. That way the swagger UI would group them based on the provided tag. So something like: 
```ts
registry.registerPath({
  method: 'GET',
  path: '/api/v1/lead/{id}',
  tags: ['YourTag'],
  ... // the rest of the reqeust/response properties and descriptions
});
```

**Comment by perry-mitchell** [comment]
Ah, you're right! Thanks @AGalabov, much appreciated..
