### ISSUE TITLE
Unable to use openapi on imported ZOD type

### ISSUE THREAD

**Issue by ZachHandley** [asteasolutions/zod-to-openapi#231]
Hey,

Trying to use this with my package [Appwrite Utils](https://github.com/zachhandley/appwriteutils) and I can't get it to work properly with my schema. I added the `openapi` definitions to my AuthUserSchema that I export. When importing and trying to use it in my ZOD types, I get an error that says

```
Property 'openapi' does not exist on type 'ZodObject<{ $id: ZodString; $createdAt: ZodOptional<ZodString>; $updatedAt: ZodOptional<ZodString>; name: ZodOptional<ZodNullable<ZodString>>; email: ZodOptional<...>; phone: ZodOptional<...>; prefs: ZodDefault<...>; labels: ZodDefault<...>; }, "strip", ZodTypeAny, { ...; }, { ...; }>'.ts(2339)
```

(it is active in this project like it's at an entrypoint)

Is there a better way to extend the types then registering it like that? Can we just import a `{ z } from "@asteasolutions/zod-to-openapi"` or something? Or maybe the verbage could be better, cause you need to technically extend it if you have your schemas in separate files in every file

**Comment by AGalabov** [comment]
@ZachHandley if I understand correctly - you can just create a file of your own that imports zod, wraps it in extendZodWithOpenApi and exports that instance so that you can use it wherever you need it. That way you would always have a modified instance of zod.

**Comment by ZachHandley** [comment]
ugh it's like I said the solution out loud and didn't pay attention lol, thank you!!!
