### ISSUE TITLE
Nested discriminated unions

### ISSUE THREAD

**Issue by vickyRathee** [asteasolutions/zod-to-openapi#239]
This was merged way back (https://github.com/colinhacks/zod/pull/1589) on Zod but I am still unable to use nested discriminated unions with `@hono/zod-openapi`. Any suggestion?

The example is taken from the refereeing PR.

![image](https://github.com/asteasolutions/zod-to-openapi/assets/6106479/788a1679-3e68-4c07-867b-dfcddac883df)

**Comment by AGalabov** [comment]
@vickyRathee this is not `@hono/zod-to-openapi` - they use our library but handle things on their own.

However for your issue - the ticket mentioned never actually got anything merged - it was closed. You can see Colin's comment here: https://github.com/colinhacks/zod/pull/1589#issuecomment-2013975822 that mentions why this would NOT be implemented and a possible alternative that can be used.

I am closing this issue.
