### ISSUE TITLE
Drizzle Zod + lazy

### ISSUE THREAD

**Issue by samducker** [asteasolutions/zod-to-openapi#255]
Hi in all of my schemas created with 'drizzle-zod' 

They cause this library to throw this error

```
{
"message": "Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.",
"data": {
"currentSchema": {
"typeName": "ZodLazy"
}
}
}
```

I have searched the issues here and not found a workaround for this apart from not using drizzle zod, which is not ideal

as the benefit of using it is that my database schema stays as the source of truth for my route definition schemas.

Do you have any workarounds or advice to overcome this issue?

**Comment by AGalabov** [comment]
@samducker sadly we do not support z.lazy as of right now and this has been the case for a while. https://github.com/asteasolutions/zod-to-openapi/discussions/191.

The main workaround would be to use the `.openapi` method and provide some manual documentation on your schema (assuming this is a one off scenario).

For example:

```ts
type Category = {
  name: string;
  subcategories: Category[];
};

const categorySchema: z.ZodType<Category> = z
  .object({
    name: z.string(),
    subcategories: z
      .lazy(() => categorySchema.array())
      .openapi({
        type: 'array',
        items: {
          $ref: '#/components/Category',
        },
      }),
  })
  .openapi('Category');
```
