### ISSUE TITLE
Feature request: multi-language support

### ISSUE THREAD

**Issue by moroine** [asteasolutions/zod-to-openapi#257]
Hello,

We need to provide our swagger in 2 languages (French & English). This is something I could be able to work on if we agree on what can be done.

I'm thinking of few scenarios here:
- Allowing passing a dictionary in `OpenApiGeneratorV31` which would replace metadata description when needed
- Allowing support of multi-language by passing an extra argument in `.openapi` like `.openapi({ description: { en: 'house', fr: 'maison' }})`

**Comment by AGalabov** [comment]
Hey @moroine I do find your idea interesting however I do not believe that this should be a part of this project. Our library provides you with the option to enter any description and put it wherever it is needed. I do not want to do this to become an "openapi builder". If anyone wants i18n you can always create a function like `createDescription` or whatever that takes a key (the regular i18n approach) and then based on an env variable or a built time argument you can make that function generate the proper description to be inputed into our library.

On a side note I found this from a simple search: https://www.npmjs.com/package/swagger-i18n-extension - no idea if it is of any use seeing its downloads.

Based on the above I will be closing this issue.

 Good luck!
