### ISSUE TITLE
Wiki auth example

### ISSUE THREAD

**Issue by JBarzdo** [asteasolutions/zod-to-openapi#26]
Hello,
I don't know if its just me or maybe it would be a good idea to add simple authentication in wiki example. Right now im a bit confused how to properly create one 😅

**Comment by georgyangelov** [comment]
Yup, I'll add one soon after I work on the change in https://github.com/asteasolutions/zod-to-openapi/pull/25 . Apologies for the delayed response, summer and all :)

**Comment by georgyangelov** [comment]
For now, you can take the output of `generator.generateDocument` and augment the resulting OpenAPI object according to your needs as described here: https://swagger.io/docs/specification/authentication/ or you can add the authentication as a header definition to your routes.
