### ISSUE TITLE
Missing multipart/form-data option

### ISSUE THREAD

**Issue by khusenov** [asteasolutions/zod-to-openapi#264]
How do I define a form-data schema to upload files in an API request? 

I couldn't find it in the documentation.

**Comment by AGalabov** [comment]
Hello @khusenov you can take a look at Open API's documentation for it - https://swagger.io/docs/specification/v3_0/describing-request-body/describing-request-body/#form-data.

In terms of an API it should be just providing the media type `multipart/form-data`. This happens as the key of a `request.body`. So it would be something like:

```ts

registry.registerPath({
  method: 'post',
  path: '/some/path',
  description: 'Multipart',
  request: {
    body: {
      content: {
        'multipart/form-data': { // note this!
          schema: z.any() // You can use any form of validation here
        },
      },
    },
  },
  responses: {
    200: {
      content: {
        'application/json': {
          schema: z.object({
            message: z.string(),
          }),
        },
      },
      description: '',
    },
  },
});
```

**Comment by khusenov** [comment]
@AGalabov Thank you for the reply.

I was thinking the same thing, but library provides only application/json. 

Maybe this is because zod doesn't support file types

Anyway, I hardcoded without using zod to solve this.

**Comment by farazalidev** [comment]
> How do I define a form-data schema to upload files in an API request?
> 
> I couldn't find it in the documentation.



`extendZodWithOpenApi(z);

storageRegistry.registerPath({
  method: "post",
  path: "/storage/product/image",
  description: "Upload an image for a product",
  tags: ["Storage"],
  request: {
    body: {
      content: {
        "multipart/form-data": {
          schema: z.object({
            image: z.string().describe("The file to upload").openapi({ format: "binary" }),
          }),
        },
      },
    },
  },
  responses: {
    200: {
      content: {
        "application/json": {
          schema: z.object({
            message: z.string(),
          }),
        },
      },
      description: "Successful file upload",
    },
  },
});`

**Comment by sfourdrinier** [comment]
Doesn't work for me. Doing this I am still getting:
{"message":"Malformed FormData request. JSON Parse error: Invalid number","stack":"Error: Malformed FormData request. JSON Parse error: Invalid number\n    at new HTTPExceptio......}

and this is my definition:

`  request: {
    body: {
      required: true,
      content: {
        "multipart/form-data": {
          schema: z.object({
            image: z
              .string()
              .describe("The file to upload")
              .openapi({ format: "binary" }),
          }),
        },
      },
      description: "Multipart form data containing the avatar image file",
    },
  },`

**Comment by farazalidev** [comment]
> Doesn't work for me. Doing this I am still getting:
> {"message":"Malformed FormData request. JSON Parse error: Invalid number","stack":"Error: Malformed FormData request. JSON Parse error: Invalid number\n    at new HTTPExceptio......}
> 
> and this is my definition:
> 
> `  request: {
>     body: {
>       required: true,
>       content: {
>         "multipart/form-data": {
>           schema: z.object({
>             image: z
>               .string()
>               .describe("The file to upload")
>               .openapi({ format: "binary" }),
>           }),
>         },
>       },
>       description: "Multipart form data containing the avatar image file",
>     },
>   },`

Do you put this line on the top of scheme registration 

`extendZodWithOpenApi(z);
`
