### ISSUE TITLE
Support for number formats

### ISSUE THREAD

**Issue by rokabakaroni** [asteasolutions/zod-to-openapi#278]
Hi, I'm new to this library. I noticed that you support `number`, `int` and `datetime` (last one as string format). Could you also add API support for double? Currently we can do

```ts
age: z.number().int().openapi({
  example: 42,
}),

bodyTemperature: z.number().openapi({
  type: "number",
  format: "double",
  example: 38.99,
}),
```

and it would be nice to have `z.number().double()`.

https://swagger.io/docs/specification/v3_0/data-models/data-types/#numbers

I guess `float` could be interesting too.

**Comment by AGalabov** [comment]
@rokabakaroni that's correct - you can specify any format you like and add some sort of validation manually but zod does not support that as an option. I am closing this issue.
