### ISSUE TITLE
Parameters inlined instead of using `$ref`?

### ISSUE THREAD

**Issue by georgyangelov** [asteasolutions/zod-to-openapi#7]
In [this example](https://github.com/asteasolutions/zod-to-openapi/blob/a554dac86bfd67e2072ddbaad8496a162dd10d5e/example/openapi-docs.yml#L42) the parameter is not using `$ref`. Why? Is this a docs issue or a library issue?

**Comment by AGalabov** [comment]
Fixed in https://github.com/asteasolutions/zod-to-openapi/pull/8
