### ISSUE TITLE
openapi3 response anyOf schema definitions

### ISSUE THREAD

**Issue by botiapa** [asteasolutions/zod-to-openapi#76]
Looking at the documentation and source code, I couldn't figure out if zod-to-openapi supports anyOf  when defining response schemas. 

Example yaml copied from swagger website:
```
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
```

As you can see there are 2 possible response schemas. However, if I understand correctly, `ResponseConfig.content[mediaType].schema` only supports a single schema at a time. Am I missing something?

**Comment by samchungy** [comment]
hey @botiapa you should be able to pass a Zod union object into your response and that will generate an `anyOf`. Everything here is ZodSchema first. So try and think about what ZodSchema you'd like as your response type and we should be mapping that properly 😄 

eg.

```
...
  responses: {
    200: {
      description: 'Successful operation',
      content: {
        'application/json': {
          schema: MyUnionSchema,
        },
      },
    },
```

**Comment by adamgarcia4** [comment]
Just want to say to @samchungy that I appreciate all the contributor's efforts on this project. This looks like exactly what we are looking for.

**Comment by AGalabov** [comment]
@botiapa yes as @samchungy said the idea of this project is to generate the documentation based on your input validations. So you shouldn't be thinking about "I want to have `anyOf` in my documentation" but rather "I want to validate that the data is one of the specified formats" and this happens using `z.union`. Using this approach and the library, we actually managed to fix some errors in our manually-written documentation in another project.

If that answers your question please go ahead and close the issue.

Thank you for using the library!

**Comment by botiapa** [comment]
@AGalabov Thank you for this wonderful library. I read both of your comments, but I'm still having some issues, which may or may not be caused by this library. I don't want to spread misinformation, so I'm currently in the process of eliminating all the other variables. So please bear with me while I do that.
