### ISSUE TITLE
Multipart upload

### ISSUE THREAD

**Issue by szuttenbach** [asteasolutions/zod-to-openapi#86]
Hello,
at first great library. Question if anyone knows how to declare multipart upload?

**Comment by AGalabov** [comment]
Hello @szuttenbach looking at the [following example:](https://swagger.io/docs/specification/describing-request-body/multipart-requests/) from swagger.io the correct way to replicate it with `@asteasolutions/zod-to-openapi` would be:

```ts
const registry = new OpenAPIRegistry();

// Please note that the formats from the example are omitted for brevity
const Schema = z.object({
  id: z.string(),
  address: z.object({
    street: z.string(),
    city: z.string(),
  }),
  profileImage: z.string(),
});

registry.registerPath({
  method: 'post',
  path: 'upload',
  request: {
    body: {
      content: {
        'multipart/form-data': {
          schema: Schema,
        },
      },
    },
  },
  responses: {},
});
```

the resulting YAML is:
```yaml
paths:
  upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                  required:
                    - street
                    - city
                profileImage:
                  type: string
              required:
                - id
                - address
                - profileImage
      responses: {}
```


Does that work for you? If yes please go ahead and close the issue. And if not, please let me know.

**Comment by szuttenbach** [comment]
Hi, thank you for the response, but string is not correct type of a binary file, so when I want to pass the file to another function as a Buffer it has incorrect type.

**Comment by szuttenbach** [comment]
I was trying to use z.instanceOf(Buffer), but then it's not generating swagger at all, so it seems that it's not supported.

**Comment by AGalabov** [comment]
Sure, yes that is a separate problem. `z.instanceof` is not supported at this point. And I am not sure if we can even implement, I'll give it a go soon. For the time being I would suggest just using `z.instanceOf(Buffer).openapi({ /*You must pass type and then everything you want*/  })` to provide your own documentation for this particular instance. That way you would still have the `Buffer` type in your code but the documentation would be generated properly.
