### ISSUE TITLE
Swagger UI to Open Api

### ISSUE THREAD

**Issue by wiltonjr22** [asteasolutions/zod-to-openapi#90]
hi,
i have a question 

<img width="854" alt="Captura de Tela 2023-02-02 às 19 08 58" src="https://user-images.githubusercontent.com/49769357/216460523-ddcca38b-d490-464d-aae1-9d9b30b7929a.png">

but when i look into file .json

![Captura de Tela 2023-02-02 às 19 10 21](https://user-images.githubusercontent.com/49769357/216460749-3109a157-7d1e-465c-8e39-ae397cc2d40a.png)

Has this happened to anyone else or would there be a solution for this case?

**Comment by samchungy** [comment]
Have you tried other validators or saving that file?

**Comment by wiltonjr22** [comment]
> Have you tried other validators or saving that file?


<img width="551" alt="Captura de Tela 2023-02-03 às 09 09 19" src="https://user-images.githubusercontent.com/49769357/216600314-2ede2b58-b91f-41f0-bb09-f12871dde685.png">

I tried yes and the file was saved when I tested it I just modified it to hit the print but the structure was like this

and in this way I am reading the file and trying to mount the swagger

**Comment by AGalabov** [comment]
@wiltonjr22 I think this is `swagger-ui-express` right. I think you are missing one thing, tho. `readFileSync` returns a string. The `swaggerUi.setup` method accepts JSON objects. I.e you should try running `JSON.parse` on the result from `readFileSync`. Can you try that?

**Comment by wiltonjr22** [comment]
> 

I already tried to directly import the json inside it, but without success too.

Do you have an example of how to do this part?

**Comment by wiltonjr22** [comment]
> @wiltonjr22 I think this is `swagger-ui-express` right. I think you are missing one thing, tho. `readFileSync` returns a string. The `swaggerUi.setup` method accepts JSON objects. I.e you should try running `JSON.parse` on the result from `readFileSync`. Can you try that?

I already tried to directly import the json inside it, but without success too.

Do you have an example of how to do this part?

**Comment by AGalabov** [comment]
Yes what we do is: 

```ts
const content = fs.readFileSync(
  path.join(__dirname, "..", "swagger.json"),
  "utf8"
);
const swaggerDoc = JSON.parse(content);
// ...

router.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDoc));
```

**Comment by bradchristensen** [comment]
Just to add another user experience to this, I've been playing around with both `zod-to-openapi` and `swagger-ui-express` today as well, and it all worked pretty seamlessly :slightly_smiling_face: 

I'm generating the spec at runtime using the following routes:

```ts
router.use("/docs", swaggerUi.serve);
router.get("/docs", (req, res, next) => {
  const generator = new OpenAPIGenerator(registry.definitions, "3.0.3");
  const swaggerDocument = generator.generateDocument({
    info: {
      title: "Some title",
      version: "1.0.0",
      description: "Some description",
    },
  });
  return swaggerUi.setup(swaggerDocument)(req, res, next);
});
```

This updates the spec and corresponding UI on each docs page request, for testing purposes. In production you'd probably want to either disable that or have it only generate once up-front.

Note that `swagger-ui-express` doesn't support OpenAPI version 3.1.0 at the time of writing, but 3.0.3 works.

**Comment by wiltonjr22** [comment]
> ```ts
![Captura de Tela 2023-02-10 às 09 34 16](https://user-images.githubusercontent.com/49769357/218093637-e6a10359-8622-487a-8ccc-c204f46e9f69.png)
<img width="436" alt="Captura de Tela 2023-02-10 às 09 34 05" src="https://user-images.githubusercontent.com/49769357/218093640-d0b220e1-2dce-4ac2-8eae-d65e321cd56c.png">

> const swaggerDoc = JSON.parse(content);
> ```

now its worked thanks, only missing is this json.parse
