### ISSUE TITLE
Include support for .describe from Zod

### ISSUE THREAD

**Issue by jakobo** [asteasolutions/zod-to-openapi#94]
Currently, descriptions for the OpenAPI definition need to live on the `.openapi()` method. However, zod already includes a [describe](https://zod.dev/?id=describe) method, which would be redundant in most cases.

I'm a bit slammed with work, but the following test demonstrates the issue. Test would be added to [/spec/metadata-overrides.spec.ts](https://github.com/asteasolutions/zod-to-openapi/blob/master/spec/metadata-overrides.spec.ts)

```ts
it("considers zod metadata if set", () => {
  const ZodMetadataSchema = registerSchema(
    "ZodMetadata",
    z.object({}).describe("Test")
  );

  const TestSchema = registerSchema(
    "Test",
    z.object({ key: ZodMetadataSchema })
  );

  expectSchema([ZodMetadataSchema, TestSchema], {
    ZodMetadataSchema: {
      type: "object",
      description: "Test",
    },
    Test: {
      type: "object",
      required: ["key"],
      properties: {
        key: {
          $ref: "#/components/schemas/ZodMetadataSchema",
        },
      },
    },
  });
});
```

**Comment by AGalabov** [comment]
@jakobo just released this in the `4.4.0` version
