### ISSUE TITLE
registerParameter is not creating component parameters

### ISSUE THREAD

**Issue by BryanL123456789** [asteasolutions/zod-to-openapi#96]
I've been using registry.registerParameter to try to create an entry in the component parameters so I can set a reference to it in my request, but it just creates an inline definition.

[snippet.txt](https://github.com/asteasolutions/zod-to-openapi/files/10853035/snippet.txt)

Am I doing something wrong?

**Comment by AGalabov** [comment]
@BryanL123456789  thank you for reporting that! It has indeed been broken with a small refactoring task and it also showcased a week spot in our tests. I just fixed it with [this PR](https://github.com/asteasolutions/zod-to-openapi/pull/97). It will be available as 4.4.1 in a few minutes.

**Comment by BryanL123456789** [comment]
Thank you very much! It works perfectly!
